### ISSUE TITLE
Thanks so much! Do you know where I can find the pre-trained weights?

### ISSUE THREAD

**Issue by jamesbaker1** [sayedmohamedscu/YOLOv8-Door-detection-for-visually-impaired-people#1]
Thank you for your contribution! I would love to try out this model. Do you know where I can find your pre-trained weights?

**Comment by sayedmohamedscu** [comment]
You are welcome @jamesbaker1 
the model uploaded in the repo , feel free to use it 
thanks 

https://github.com/sayedmohamedscu/YOLOv8-Door-detection-for-visually-impaired-people/blob/main/doors.pt

![image](https://github.com/user-attachments/assets/80f5f082-e5a0-40a5-9c06-6493c510603f)
